<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Role;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{
  public function __construct(EntityManagerInterface $em, Mapping\ClassMetadata $metadata = null)
  {
    parent::__construct($em, $metadata == null ? new Mapping\ClassMetadata(Role::class) : $metadata);
  }
}
