<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\ORMException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
  public function __construct(EntityManagerInterface $em, Mapping\ClassMetadata $metadata = null)
  {
    parent::__construct($em, $metadata == null ? new Mapping\ClassMetadata(User::class) : $metadata);
  }

  public function insert(User $user)
  {

    try {
      $this->_em->persist($user);
      $this->_em->flush();
      return true;
    } catch (OptimisticLockException $e) {
      return true;
    } catch (ORMException $e) {
    }
    return true;
  }
}
